### ISSUE TITLE
jar knows parameter --file instead of --archive

### ISSUE THREAD

**Issue by torstenwerner** [cbeams/jigsaw-quick-start#1]
Thanks for the quick start. I have tried to use it with the current early access release of jdk 9 that already contains the jigsaw system. But I had a problem with the --archive parameter of jar which is used in your step.sh but which is not supported. The correct parameter seems to be --file. Maybe it is worth fixing it.

**Comment by cbeams** [comment]
Thanks, @torstenwerner. At the time I wrote the quick start, it was the other way around: `--archive` was supported, but `--file` was not (even though the official Jigsaw docs used the latter).

**Comment by cbeams** [comment]
`master` now reflects `jar` options available in JDK 9 ea b111. See 69b4fdd69c0c6e32afa59b746be7e1c532602c5f for details.
