### ISSUE TITLE
`-modulepath` is now `--module-path`

### ISSUE THREAD

**Issue by snicoll** [cbeams/jigsaw-quick-start#2]
The module path option has been renamed in the latest release apparently. I am using 

```
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+140)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+140, mixed mode)
```

The following at step1 fixed it for me.

``` diff
diff --git a/step.sh b/step.sh
index 37b0c9f..07060a0 100755
--- a/step.sh
+++ b/step.sh
@@ -36,5 +36,5 @@ task
 set -x

 java \
-    -modulepath bin \
+    --module-path bin \
     -m com.greetings/com.greetings.Main
```

**Comment by cbeams** [comment]
Thanks @snicoll, will get to this as I have time. It's a bit involved to update the steps (see 69b4fdd69c0c6e32afa59b746be7e1c532602c5f for a previous example). In the meantime, at least this issue is here to help other folks who run into the same thing.

**Comment by andretadeu** [comment]
For what it's worth I forked this repo, transformed the tags step1 to step9 into branches, fixed the javac and java parameters in each branch, and fixed the master branch. This seems to be a reasonable way to keep this repository updated with JDK 9 changes.

**Comment by cbeams** [comment]
`-modulepath` has been replaced with `--module-path` everywhere, updated commits have been force-pushed and tags have been updated accordingly. Everything should work as advertised now against the latest JDK 9 early access builds. Thanks.
