### ISSUE TITLE
may be fix the step to checkout specific step?

### ISSUE THREAD

**Issue by pradhyu** [cbeams/jigsaw-quick-start#3]
I am not sure why the statement treated the steps as branches, i don't see any branches but tags when i cloned the repo. 

The steps are created as tags not branches 
so instead of 
   **git checkout step0** 
we should do 
   **git checkout tags/step0**
to checkout the specific step. 

Am I missing something here ?

**Comment by cbeams** [comment]
The steps are indeed modeled as tags, and checking them out by name—a la `git checkout step0`—works as advertised in the `git-checkout` manpage:

```
git checkout [-p|--patch] [<tree-ish>] [--] <pathspec>...
        [...] The <tree-ish> argument
        can be used to specify a specific tree-ish (i.e. commit, tag or tree) to update the
        index for the given paths before updating the working tree.
```

**Comment by cbeams** [comment]
Closing per previous comment.
